In [4]:
import numpy as np

In [2]:
n1 = np.array([10,20,30,40])

In [3]:
n1

array([10, 20, 30, 40])

In [9]:
n2 = np.array([[10,40,80,90],[40,90,100,600]])
n2

array([[ 10,  40,  80,  90],
       [ 40,  90, 100, 600]])

In [7]:
type(n1)

numpy.ndarray

In [10]:
type(n2)

numpy.ndarray

In [14]:
#np_zeros

n1=np.zeros((1,2))
n1

array([[0., 0.]])

In [15]:
n2= np.zeros((3,3))
n2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
#same value with full

n1 = np.full((3,3),6)
n1

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [17]:
#np arange

n1 = np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
n2 = np.arange(10,50,5)
n2

array([10, 15, 20, 25, 30, 35, 40, 45])

In [20]:
#array with random numbers

n4 = np.random.randint(1,100,10)
n4


array([69, 32, 25, 21, 51, 29, 46, 21, 60, 63])

In [1]:
#####numpy operators #######

In [5]:
#shape of numpy array
import numpy as np
n1 = np.array([[1,2,3,4],[3,4,6,7]])
n1.shape

(2, 4)

In [6]:
n1.shape = (4,2)
n1.shape


(4, 2)

In [7]:
n1

array([[1, 2],
       [3, 4],
       [3, 4],
       [6, 7]])

In [12]:
n4 = np.array([10,70,80,40])
n5 = np.array([30,90,20,50])

# np.vstack((n5,n4))
# np.hstack((n5,n4))
np.column_stack((n5,n4))

array([[30, 10],
       [90, 70],
       [20, 80],
       [50, 40]])

In [13]:
import numpy as np

n6 = np.array([4,8,9,6,5])
n7 = np.array([5,7,6,3,2])

np.intersect1d(n6,n7)

array([5, 6])

In [14]:
np.setdiff1d(n7,n6)

array([2, 3, 7])

In [16]:
np.setdiff1d(n6,n7)

array([4, 8, 9])

In [17]:
######### numpy mathematics ########

In [19]:
# addition of numpy arrays

import numpy as np

n1 = np.array([10,20])
n2 = np.array([30,40])

np.sum((n1,n2))

100

In [20]:
np.sum((n1,n2), axis=0)

array([40, 60])

In [21]:
np.sum((n1,n2), axis=1)

array([30, 70])

In [22]:
n1 = np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [23]:
n1 = n1+1
n1

array([11, 21, 31, 41])

In [24]:
n1 = n1-1
n1

array([10, 20, 30, 40])

In [25]:
n1 = n1*2
n1

array([20, 40, 60, 80])

In [26]:
n1 = n1/2
n1

array([10., 20., 30., 40.])

In [27]:
n2 = np.array([10,79,66,44,32,90])

In [28]:
n2

array([10, 79, 66, 44, 32, 90])

In [29]:
np.mean(n2)

53.5

In [30]:
np.median(n2)

55.0

In [31]:
np.std(n2)

27.639042433967692

In [32]:
#######numpy matrix #######

In [34]:
n7 =  np.array([[1,2,3],[4,5,6],[7,8,9]])
n7

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
n7[0]

array([1, 2, 3])

In [37]:
n7[2]

array([7, 8, 9])

In [38]:
n7[:,1]

array([2, 5, 8])

In [39]:
n7[:,2]

array([3, 6, 9])

In [40]:
np.transpose(n7)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [41]:
n8 = np.array([[9,8,7],[6,5,4],[3,2,1]])

In [42]:
n8

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [43]:
n7

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
n7.dot(n8)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [45]:
n8.dot(n7)

array([[ 90, 114, 138],
       [ 54,  69,  84],
       [ 18,  24,  30]])

In [46]:
n9 = np.array([10,80,90,50,70])
n9

array([10, 80, 90, 50, 70])

In [51]:
np.save('my array', n9)

In [52]:
n10 = np.load('my array.npy')
n10

array([10, 80, 90, 50, 70])